#!/usr/bin/python
"""
parser for rounding loss log generated by matlab fixed-point library rounding functions
"""
import numpy as np
import re
import argparse
from collections import defaultdict

parser = argparse.ArgumentParser(description="process rounding loss log")
parser.add_argument('filename', default='/nas/users/sgowda/rounding_loss')
args = parser.parse_args()
filename = args.filename

rounding_loss = defaultdict(list)
file = open(filename, 'r')

pattern = '^(\w+): originally (\d+) bits, now (\d+) bits, loss = (.*?)$' 
regex = re.compile(pattern)
for line in file:
    m = regex.match(line)

    block         = m.group(1)
    orig_bitwidth = float(m.group(2))
    new_bitwidth  = float(m.group(3))
    loss          = float(m.group(4))

    op = (block, orig_bitwidth, new_bitwidth)
    rounding_loss[op].append(loss)


